language: node_js
cache:
  directories:
    - node_modules
node_js:
- lts/*
before_install:
- git fetch --unshallow
script:
- npm run extractor
after_success:
- chmod +x .travis/push.sh
- .travis/push.sh
